### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by Erofili-K** [GervinFung/SimpleParallelChessAI#6]
Also, i would like to add a few other issues I saw while I was ruuning the code. First, when playing with the AI after i put it to level 2 and higher it takes forever to make a move (in a particular moment it took about 1.30 min ) and when i put it in level 6 it crushed after some time. (first screenshot)
Secondly ,  (2nd and 3rd screenshots) ,  i did the same moves (left and right) , so did the AI and it never ended (i had to manually end the game if i wanted to start a new one) . What i mean is that even though it is in a position that there is no way i (white) can get out , the game lets me do infinate loops of the same moves resulting in being stuck.  
I hope this makes sesne 
thank you
![Στιγμιότυπο οθόνης (1232)](https://user-images.githubusercontent.com/72342153/154326038-b789dc3c-0b8d-4a00-8fc5-aa7b2847e645.png)
![Στιγμιότυπο οθόνης (1237)](https://user-images.githubusercontent.com/72342153/154326478-15139346-468d-4ece-81fe-e4b41e0f57b6.png)
![Στιγμιότυπο οθόνης (1238)](https://user-images.githubusercontent.com/72342153/154326485-9d56cec4-8c41-46f6-ad1d-39db4a689602.png)

**Comment by GervinFung** [comment]
> Also, i would like to add a few other issues I saw while I was ruuning the code. First, when playing with the AI after i put it to level 2 and higher it takes forever to make a move (in a particular moment it took about 1.30 min ) and when i put it in level 6 it crushed after some time. (first screenshot) Secondly , (2nd and 3rd screenshots) , i did the same moves (left and right) , so did the AI and it never ended (i had to manually end the game if i wanted to start a new one) . What i mean is that even though it is in a position that there is no way i (white) can get out , the game lets me do infinate loops of the same moves resulting in being stuck. I hope this makes sesne thank you ![Στιγμιότυπο οθόνης (1232)](https://user-images.githubusercontent.com/72342153/154326038-b789dc3c-0b8d-4a00-8fc5-aa7b2847e645.png) ![Στιγμιότυπο οθόνης (1237)](https://user-images.githubusercontent.com/72342153/154326478-15139346-468d-4ece-81fe-e4b41e0f57b6.png) ![Στιγμιότυπο οθόνης (1238)](https://user-images.githubusercontent.com/72342153/154326485-9d56cec4-8c41-46f6-ad1d-39db4a689602.png)

I understand the issues you mentioned. I will explain the reason both cases happened to the best of my ability
#### The first case
The AI in this case is multi-threaded, probably level 6 consume too much resources, so multithreading in this case backfires.

#### The second case
The AI in this case made the best move it can to counter the move you made, that's why it's repeating, this happens because it lacks a bit of randomness to make it appear more human-like - ***to not pick the best move everytime***

Now that I have explained it, I am unfortunate to inform you that I am not actively maintaining this repository and have no intention of implementing any changes. Still thank you for using it and pointing out these issues to me, it means a lot to me, keep up the spirit
